apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      {{- if .Values.dockerregistry.enabled }}
      imagePullSecrets:
        - name: dockerregistry-secret
      {{- end }}
      containers:
        - name: vproapp
          image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
          imagePullPolicy: Always
          ports:
            - name: vproapp-port
              containerPort: {{ .Values.app.containerPort }}
      initContainers:
        - name: init-mydb
          image: "{{ .Values.initcontainers.image }}:{{ .Values.initcontainers.tag }}"
          command: ["sh", "-c", {{ .Values.initcontainers.dbCommand | quote }}]
        - name: init-memcache
          image: "{{ .Values.initcontainers.image }}:{{ .Values.initcontainers.tag }}"
          command: ["sh", "-c", {{ .Values.initcontainers.memcachedCommand | quote }}]