{{- if .Values.dockerregistry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: dockerregistry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":%s,\"password\":%s,\"email\":%s,\"auth\":%s}}}" .Values.dockerregistry.server (.Values.dockerregistry.username | quote) (.Values.dockerregistry.password | quote) (.Values.dockerregistry.email | quote) (printf "%s:%s" .Values.dockerregistry.username .Values.dockerregistry.password | b64enc | quote) | b64enc | quote }}
{{- end }}