apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  ports:
    - port: {{ .Values.app.servicePort }}
      protocol: TCP
      targetPort: vproapp-port
  selector:
    app: vproapp
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: vprodb
spec:
  ports:
    - port: {{ .Values.db.servicePort }}
      protocol: TCP
      targetPort: vprodb-port
  selector:
    app: vprodb
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  ports:
    - port: {{ .Values.memcached.servicePort }}
      protocol: TCP
      targetPort: vpromc-port
  selector:
    app: vpromc
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:
  ports:
    - port: {{ .Values.rabbitmq.servicePort }}
      protocol: TCP
      targetPort: vpromq01-port
  selector:
    app: vpromq01
  type: ClusterIP